name: Blogger Auto Share

on:
  schedule:
    - cron: '*/0.1 * * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      RSS_URL: ${{ secrets.RSS_URL }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install feedparser requests

      - name: Run script
        run: |
          python scripts/check_feed.py
